#!/usr/bin/env python
"""Build the donor-resolved Figure 1 and install its manuscript figure files.

The integrated panel atlas contains non-skin libraries, repeated libraries from
the same participant and one duplicated reprocessing cohort. This renderer uses
the audited sample-to-donor map to retain only non-redundant SSc/HC skin cells.
Panel c reads the beta-binomial donor-composition outputs generated by
``01_scrna_atlas/04_donor_composition.py``. The donor-balanced seven-state
marker plot is installed as Supplementary Figure S1.
"""

from __future__ import annotations

import shutil
import sys
import warnings
from pathlib import Path

import anndata as ad
import matplotlib.patheffects as pe
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd


warnings.filterwarnings("ignore")
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import figstyle as fs  # noqa: E402


ROOT = Path(__file__).resolve().parents[2]
ARCH = ROOT / "server_archive" / "fig_atlas"
DONOR_MAP = (
    ROOT
    / "04_manuscript"
    / "revision_20260722"
    / "donor_metadata"
    / "outputs"
    / "sample_to_donor.csv"
)
REVISION_OUT = ROOT / "04_manuscript" / "revision_20260722" / "figure1" / "outputs"
COMPOSITION_SOURCE = REVISION_OUT / "Figure1c_source_data.csv"
COMPOSITION_STATS = REVISION_OUT / "Figure1c_glmmTMB_results.csv"
MARKER_PDF = REVISION_OUT / "Figure1_marker_fibroblast_states.pdf"
FIGURE_STEM = ROOT / "03_results_figures" / "figures" / "fig1_landscape"
MANUSCRIPT_FIGURES = ROOT / "04_manuscript" / "manuscript_final" / "figures"

CELLTYPE_ORDER = [
    "Fibroblast",
    "Keratinocyte",
    "Endothelial",
    "Lymphatic",
    "Pericyte",
    "SmoothMuscle",
    "Myeloid",
    "Tcell",
    "NK",
    "Bcell",
    "Plasma",
    "Mast",
    "pDC",
    "Melanocyte",
]
CELLTYPE_DISPLAY = {
    "SmoothMuscle": "Smooth muscle",
    "Tcell": "T cell",
    "Bcell": "B cell",
    "pDC": "pDC",
}
CELLTYPE_COLORS = [
    "#0072B2",
    "#E69F00",
    "#009E73",
    "#CC79A7",
    "#56B4E9",
    "#D55E00",
    "#332288",
    "#88CCEE",
    "#44AA99",
    "#117733",
    "#999933",
    "#DDCC77",
    "#AA4499",
    "#882255",
]

SUBTYPE_ORDER = [
    "Myofibroblast",
    "SFRP4_proFib",
    "SFRP2_DPP4",
    "Adipogenic",
    "FMO1_LSP1",
    "LGR5_Gur",
    "Inflammatory",
]
SUBTYPE_DISPLAY = {
    "Myofibroblast": "Myofibroblast",
    "SFRP4_proFib": "SFRP4+ pro-fibrotic",
    "SFRP2_DPP4": "SFRP2+/DPP4+",
    "Adipogenic": "Adipogenic",
    "FMO1_LSP1": "FMO1+/LSP1+",
    "LGR5_Gur": "LGR5+",
    "Inflammatory": "Inflammatory-like*",
}
SUBTYPE_COLORS = {
    "Myofibroblast": "#D55E00",
    "SFRP4_proFib": "#E69F00",
    "SFRP2_DPP4": "#0072B2",
    "Adipogenic": "#CC79A7",
    "FMO1_LSP1": "#009E73",
    "LGR5_Gur": "#56B4E9",
    "Inflammatory": "#777777",
}
COHORT_COLORS = {
    "Gur_GSE195452": "#0072B2",
    "GSE249279": "#E69F00",
    "Tabib_GSE138669": "#009E73",
    "GSE292979": "#CC79A7",
    "GSE236111": "#56B4E9",
}
CONDITION_COLORS = {"HC": "#2166AC", "SSc": "#D55E00"}
COMPOSITION_ORDER = ["Fibroblast"] + SUBTYPE_ORDER
COMPOSITION_DISPLAY = {"Fibroblast": "Fibroblast total", **SUBTYPE_DISPLAY}


def load_audited_atlas() -> tuple[ad.AnnData, ad.AnnData, dict]:
    donor_map = pd.read_csv(DONOR_MAP, dtype={"sample": str, "donor_id": str})
    donor_map["analysis_keep"] = (
        donor_map["analysis_keep"].astype(str).str.lower().eq("true")
    )
    kept = donor_map.loc[
        donor_map["analysis_keep"], ["sample", "donor_id", "cohort", "condition"]
    ].copy()
    if kept["sample"].duplicated().any():
        raise ValueError("Audited retained sample identifiers are not unique")
    sample_to_donor = kept.set_index("sample")["donor_id"]

    atlas = ad.read_h5ad(ARCH / "atlas_fig.h5ad")
    sample = atlas.obs["sample"].astype(str)
    atlas = atlas[sample.isin(kept["sample"])].copy()
    atlas.obs["sample"] = atlas.obs["sample"].astype(str)
    atlas.obs["donor_id"] = atlas.obs["sample"].map(sample_to_donor)

    fibro = ad.read_h5ad(ARCH / "fib_fig.h5ad")
    fibro = fibro[fibro.obs_names.isin(atlas.obs_names)].copy()
    if atlas.n_obs != 325_636 or atlas.obs["donor_id"].nunique() != 230:
        raise ValueError(
            "Audited Figure 1 population changed: "
            f"{atlas.n_obs:,} cells and {atlas.obs['donor_id'].nunique()} donors"
        )
    assigned_fibroblasts = int(
        (
            atlas.obs["celltype"].astype(str).eq("Fibroblast")
            & atlas.obs["fib_subtype"].astype(str).isin(SUBTYPE_ORDER)
        ).sum()
    )
    if fibro.n_obs != assigned_fibroblasts:
        raise ValueError("Fibroblast UMAP no longer matches retained state-labelled cells")
    audit = {
        "cells": int(atlas.n_obs),
        "donors": int(atlas.obs["donor_id"].nunique()),
        "cohorts": int(kept["cohort"].nunique()),
        "ssc_donors": int(kept.loc[kept["condition"].eq("SSc"), "donor_id"].nunique()),
        "hc_donors": int(kept.loc[kept["condition"].eq("HC"), "donor_id"].nunique()),
    }
    return atlas, fibro, audit


def draw_umap(
    ax: plt.Axes,
    adata: ad.AnnData,
    key: str,
    order: list[str],
    colors: dict[str, str],
    display: dict[str, str],
    title: str,
    point_size: float,
    show_legend: bool = False,
) -> None:
    embedding = np.asarray(adata.obsm["X_umap"])
    labels = adata.obs[key].astype(str).to_numpy()
    rng = np.random.default_rng(20260723)
    draw_order = rng.permutation(len(labels))
    ax.scatter(
        embedding[draw_order, 0],
        embedding[draw_order, 1],
        s=point_size,
        c=[colors.get(label, "#D9D9D9") for label in labels[draw_order]],
        alpha=0.78,
        linewidths=0,
        rasterized=True,
    )
    for label in order:
        points = embedding[labels == label]
        if not len(points):
            continue
        centre = np.median(points, axis=0)
        label_text = display.get(label, label)
        if label == "Inflammatory":
            ax.annotate(
                label_text,
                xy=centre,
                xytext=(20, 15),
                textcoords="offset points",
                fontsize=7.2,
                fontweight="bold",
                color="#333333",
                arrowprops={"arrowstyle": "-", "color": "#555555", "lw": 0.8},
                path_effects=[pe.withStroke(linewidth=2.2, foreground="white")],
            )
        else:
            ax.text(
                centre[0],
                centre[1],
                label_text,
                fontsize=6.6 if key == "celltype" else 7.2,
                fontweight="bold",
                ha="center",
                va="center",
                path_effects=[pe.withStroke(linewidth=2.2, foreground="white")],
            )
    ax.set_title(title, fontsize=10.5, fontweight="bold", pad=5)
    ax.set_xlabel("UMAP1", fontsize=8)
    ax.set_ylabel("UMAP2", fontsize=8)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.spines[:].set_visible(False)
    if show_legend:
        handles = [
            Line2D(
                [0], [0], marker="o", linestyle="", markersize=5.5,
                markerfacecolor=colors[label], markeredgecolor="white",
                label=display.get(label, label),
            )
            for label in order
            if label in labels
        ]
        ax.legend(
            handles=handles,
            loc="lower center",
            bbox_to_anchor=(0.5, -0.17),
            ncol=4,
            frameon=False,
            fontsize=6.5,
            columnspacing=1.0,
            handletextpad=0.35,
        )


def draw_box(ax: plt.Axes, values: np.ndarray, x: float, color: str) -> None:
    if not len(values):
        return
    ax.boxplot(
        values,
        positions=[x],
        widths=0.36,
        patch_artist=True,
        showfliers=False,
        medianprops={"color": color, "linewidth": 1.2},
        boxprops={"facecolor": "white", "edgecolor": color, "linewidth": 1.0},
        whiskerprops={"color": color, "linewidth": 0.9},
        capprops={"color": color, "linewidth": 0.9},
    )


def q_label(value: float) -> str:
    return "<0.001" if value < 0.001 else f"={value:.3f}"


def p_label(value: float) -> str:
    return "<0.001" if value < 0.001 else f"={value:.3f}"


def draw_composition(ax: plt.Axes, endpoint: str, source: pd.DataFrame, stats: pd.DataFrame) -> None:
    data = source[source["endpoint"].eq(endpoint)].copy()
    rng = np.random.default_rng(20260723 + COMPOSITION_ORDER.index(endpoint))
    for x, condition in enumerate(["HC", "SSc"]):
        group = data[data["condition"].eq(condition)]
        values = group["fraction"].to_numpy(float) * 100
        draw_box(ax, values, x, CONDITION_COLORS[condition])
        ax.scatter(
            x + rng.normal(0, 0.075, len(group)),
            values,
            s=11,
            c=[COHORT_COLORS.get(cohort, "#777777") for cohort in group["cohort"]],
            alpha=0.58,
            edgecolors="white",
            linewidths=0.25,
            rasterized=True,
            zorder=3,
        )
    max_value = float(data["fraction"].max() * 100) if len(data) else 0.0
    upper = max(1.0, max_value * 1.30)
    if endpoint == "Fibroblast":
        upper = min(102.0, upper)
    ax.set_ylim(0, upper)
    ax.set_xlim(-0.55, 1.55)
    ax.set_xticks([0, 1], ["HC", "SSc"])
    ax.set_title(COMPOSITION_DISPLAY[endpoint], fontsize=8.7, fontweight="bold", pad=4)
    row = stats.loc[endpoint] if endpoint in stats.index else None
    if row is not None and np.isfinite(row.get("OR", np.nan)):
        ax.text(
            0.98,
            0.97,
            f"OR {row.OR:.2f} [{row.CI_low:.2f}, {row.CI_high:.2f}]\n"
            f"BH q{q_label(float(row.q_BH))}; Holm p{p_label(float(row.p_Holm))}",
            transform=ax.transAxes,
            ha="right",
            va="top",
            fontsize=6.1,
            bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.80, "pad": 1.0},
        )
    elif endpoint == "Inflammatory":
        ax.text(
            0.98,
            0.97,
            "Not estimable",
            transform=ax.transAxes,
            ha="right",
            va="top",
            fontsize=6.1,
        )
    if endpoint == "Inflammatory":
        ax.text(
            0.02,
            0.97,
            f"{int(data['count'].sum())} cells; {int((data['count'] > 0).sum())} donor",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=6.1,
        )
    ax.tick_params(axis="both", labelsize=7)
    ax.grid(axis="y", color="#E5E5E5", linewidth=0.6, zorder=0)
    ax.spines[["top", "right"]].set_visible(False)


def build_figure() -> dict:
    atlas, fibro, audit = load_audited_atlas()
    source = pd.read_csv(COMPOSITION_SOURCE)
    stats = pd.read_csv(COMPOSITION_STATS)
    stats = stats[
        stats["family"].eq("fibro_primary")
        & stats["denominator"].eq("all_skin_cells")
        & stats["omitted_cohort"].eq("none")
    ].set_index("endpoint")

    fig = plt.figure(figsize=(14.2, 10.8))
    grid = GridSpec(
        3,
        4,
        figure=fig,
        height_ratios=[1.18, 0.92, 0.92],
        hspace=0.48,
        wspace=0.34,
        left=0.065,
        right=0.985,
        top=0.965,
        bottom=0.075,
    )
    ax_a = fig.add_subplot(grid[0, :2])
    celltype_colors = dict(zip(CELLTYPE_ORDER, CELLTYPE_COLORS))
    draw_umap(
        ax_a,
        atlas,
        "celltype",
        CELLTYPE_ORDER,
        celltype_colors,
        CELLTYPE_DISPLAY,
        f"Non-redundant skin atlas: {audit['cells']:,} cells from {audit['donors']} donors",
        point_size=1.15,
    )
    fs.panel_label(ax_a, "a")

    ax_b = fig.add_subplot(grid[0, 2:])
    draw_umap(
        ax_b,
        fibro,
        "fib_subtype",
        SUBTYPE_ORDER,
        SUBTYPE_COLORS,
        SUBTYPE_DISPLAY,
        f"Fibroblast states: {fibro.n_obs:,} cells",
        point_size=1.8,
        show_legend=True,
    )
    fs.panel_label(ax_b, "b")

    composition_axes: list[plt.Axes] = []
    for position, endpoint in enumerate(COMPOSITION_ORDER):
        row = 1 + position // 4
        column = position % 4
        ax = fig.add_subplot(grid[row, column])
        draw_composition(ax, endpoint, source, stats)
        if column == 0:
            ax.set_ylabel("Fraction of all skin cells (%)", fontsize=7.5)
        composition_axes.append(ax)
    fs.panel_label(composition_axes[0], "c")

    cohort_handles = [
        Line2D(
            [0], [0], marker="o", linestyle="", markerfacecolor=color,
            markeredgecolor="white", markersize=5.2, label=cohort,
        )
        for cohort, color in COHORT_COLORS.items()
    ]
    fig.legend(
        handles=cohort_handles,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.012),
        ncol=len(cohort_handles),
        frameon=False,
        fontsize=7,
        title="Cohort",
        title_fontsize=7.5,
    )
    fig.text(
        0.985,
        0.01,
        "* Inflammatory-like: 54 cells from one HC donor; descriptive only.",
        ha="right",
        va="bottom",
        fontsize=6.7,
    )

    FIGURE_STEM.parent.mkdir(parents=True, exist_ok=True)
    REVISION_OUT.mkdir(parents=True, exist_ok=True)
    MANUSCRIPT_FIGURES.mkdir(parents=True, exist_ok=True)
    fs.save_fig(fig, str(FIGURE_STEM))
    fs.save_fig(fig, str(REVISION_OUT / "Figure1_revised"))
    plt.close(fig)
    shutil.copy2(FIGURE_STEM.with_suffix(".pdf"), MANUSCRIPT_FIGURES / "Fig1.pdf")
    if not MARKER_PDF.exists():
        raise FileNotFoundError(f"Run 05_fibroblast_marker_evidence.py first: {MARKER_PDF}")
    shutil.copy2(MARKER_PDF, MANUSCRIPT_FIGURES / "FigS1.pdf")
    return audit


if __name__ == "__main__":
    result = build_figure()
    print(
        "Figure 1 complete: "
        f"{result['cells']:,} skin cells, {result['donors']} donors "
        f"({result['ssc_donors']} SSc, {result['hc_donors']} HC), "
        f"{result['cohorts']} non-redundant cohorts"
    )
