"""Figure 6: candidate perivascular Notch signalling to myofibroblast HES1.

Panel b uses the audited sender-derived bona fide ligand universe generated by
``06_ccc_nichenet/02b_audit_rerank_ligands.py``.  It must never fall back to
the unfiltered NicheNet ``lr_network$from`` universe.
"""

import os
import sys
from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpec
from matplotlib.lines import Line2D

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import figstyle as fs


ROOT = Path(__file__).resolve().parents[2]
DL = ROOT / "04_manuscript" / "plot_data_local" / "ccc_nichenet"
CHORD = ROOT / "03_results_figures" / "figures" / "Fig6b_ccc_chord.png"
D_SOURCE = DL / "donor_notch_receiver" / "Figure6d_source_data.csv"
E_PANEL = ROOT / "04_manuscript" / "revision_20260722" / "figure6_spatial" / "outputs" / "Figure6e_Xenium_mask_shared_edge_adjacency.png"
OUT = ROOT / "04_manuscript" / "manuscript_final" / "figures" / "Fig6"
NOTCH_LIG = ["DLL1", "DLL3", "DLL4", "JAG1", "JAG2"]
TGFB = ["TGFB1", "TGFB2", "TGFB3"]
COHORT_COLORS = {
    "Gur_GSE195452": "#0072B2",
    "GSE249279": "#E69F00",
    "Tabib_GSE138669": "#009E73",
    "GSE292979": "#CC79A7",
    "GSE236111": "#56B4E9",
}


def crop_white(img, threshold=250, pad=10):
    """Trim near-white borders from embedded raster panels."""
    arr = np.asarray(img)
    rgb = arr[..., :3]
    mask = np.any(rgb < threshold / 255 if rgb.dtype.kind == "f" else rgb < threshold, axis=2)
    if not mask.any():
        return arr
    y, x = np.where(mask)
    y0, y1 = max(int(y.min()) - pad, 0), min(int(y.max()) + pad + 1, arr.shape[0])
    x0, x1 = max(int(x.min()) - pad, 0), min(int(x.max()) + pad + 1, arr.shape[1])
    return arr[y0:y1, x0:x1]

lig = pd.read_csv(DL / "nichenet" / "ligand_activities_bona_fide.csv")
ntl = pd.read_csv(DL / "nichenet" / "notch_ligand_target_links.csv")
expr = pd.read_csv(DL / "export" / "notch_expr_fraction.csv")
donor = pd.read_csv(D_SOURCE)

fig = plt.figure(figsize=(13.8, 10.6))
gs = GridSpec(
    3,
    2,
    width_ratios=[1.28, 1.0],
    height_ratios=[1, 1, 1.05],
    wspace=0.32,
    hspace=0.50,
    figure=fig,
)

# ===== A: chord (embedded high-resolution image) =====
axA = fig.add_subplot(gs[:2, 0])
if CHORD.exists():
    axA.imshow(crop_white(mpimg.imread(CHORD), pad=25))
    axA.axis("off")
else:
    axA.text(0.5, 0.5, "chord missing", ha="center")
    axA.axis("off")

# ===== B: audited NicheNet ligand activity =====
axB = fig.add_subplot(gs[0, 1])


def lcolor(gene):
    if gene in NOTCH_LIG:
        return fs.LEAD_BLUE
    if gene in TGFB:
        return fs.CTRL_COLOR
    return "#BDBDBD"


la = lig.sort_values("aupr_corrected", ascending=False).head(12).iloc[::-1]
cols = [lcolor(gene) for gene in la.test_ligand]
y = np.arange(len(la))
axB.hlines(y, 0, la.aupr_corrected, color=cols, lw=2.0)
axB.scatter(
    la.aupr_corrected,
    y,
    color=cols,
    s=44,
    zorder=3,
    edgecolor="white",
    linewidth=0.5,
)
axB.set_yticks(y)
axB.set_yticklabels(la.test_ligand, fontsize=7.6)
for tick, gene in zip(axB.get_yticklabels(), la.test_ligand):
    if gene in NOTCH_LIG:
        tick.set_fontweight("bold")
        tick.set_color(fs.LEAD_BLUE)
dll4 = int(lig.loc[lig.test_ligand == "DLL4", "rank"].iloc[0])
n_ligands = int(lig["n_ligands"].iloc[0])
axB.set_xlabel("ligand activity (AUPR corrected)", fontsize=8)
axB.set_title(
    f"Bona fide ligand drivers (DLL4 rank {dll4}/{n_ligands})", fontsize=9
)
axB.legend(
    handles=[
        Line2D(
            [0],
            [0],
            marker="o",
            color="w",
            markerfacecolor=fs.CTRL_COLOR,
            ms=7,
            label="TGF-beta control",
        ),
        Line2D(
            [0],
            [0],
            marker="o",
            color="w",
            markerfacecolor=fs.LEAD_BLUE,
            ms=7,
            label="Notch ligand",
        ),
        Line2D(
            [0],
            [0],
            marker="o",
            color="w",
            markerfacecolor="#BDBDBD",
            ms=7,
            label="Other ligand",
        ),
    ],
    loc="lower right",
    fontsize=6.2,
)
axB.set_xlim(0, la.aupr_corrected.max() * 1.15)
fs.despine(axB)

# ===== C: Notch ligand -> target heatmap =====
axC = fig.add_subplot(gs[1, 1])
piv = ntl.pivot_table(index="ligand", columns="target", values="weight", aggfunc="mean")
tord = [target for target in ["HES1", "ACTA2", "FN1"] if target in piv.columns]
lord = [gene for gene in ["DLL4", "JAG1", "DLL1", "JAG2"] if gene in piv.index]
piv = piv.loc[lord, tord]
im = axC.imshow(piv.values, cmap="viridis", aspect="auto", vmin=0)
axC.set_xticks(range(len(tord)))
axC.set_xticklabels(tord, fontsize=8, fontweight="bold")
axC.set_yticks(range(len(lord)))
axC.set_yticklabels(lord, fontsize=8, fontweight="bold")
mx = np.nanmax(piv.values)
for i in range(len(lord)):
    for j in range(len(tord)):
        value = piv.values[i, j]
        if not np.isnan(value):
            axC.text(
                j,
                i,
                f"{value:.02f}",
                ha="center",
                va="center",
                color="white" if value < mx * 0.6 else "black",
                fontsize=7.5,
            )
axC.set_title("Notch ligand -> target potential", fontsize=9)
axC.set_xlabel("target", fontsize=8)
axC.set_ylabel("Notch ligand", fontsize=8)
fig.colorbar(im, ax=axC, fraction=0.046, pad=0.03).set_label(
    "reg. potential", fontsize=7
)

# ===== D: donor-level receiver expression =====
subD = gs[2, 0].subgridspec(2, 2, wspace=0.28, hspace=0.62)
genes = ["NOTCH1", "NOTCH2", "NOTCH3", "HES1"]
mainD = donor.drop_duplicates("gene").set_index("gene")
rng = np.random.default_rng(20260723)
denom = np.sqrt(donor["total"].to_numpy())
denom_min, denom_max = float(np.nanmin(denom)), float(np.nanmax(denom))
axesD = []
for i, gene in enumerate(genes):
    ax = fig.add_subplot(subD[i // 2, i % 2], sharey=axesD[0] if axesD else None)
    axesD.append(ax)
    gd = donor[donor.gene == gene]
    for xi, cond in enumerate(["HC", "SSc"]):
        d = gd[gd.condition == cond]
        jitter = rng.normal(0, 0.055, size=len(d))
        ds = np.sqrt(d["total"].to_numpy())
        if denom_max > denom_min:
            sizes = 7 + (ds - denom_min) / (denom_max - denom_min) * 42
        else:
            sizes = np.repeat(18, len(d))
        ax.scatter(
            np.repeat(xi, len(d)) + jitter,
            d["fraction"],
            s=sizes,
            c=[COHORT_COLORS.get(cohort, "#777777") for cohort in d["cohort"]],
            alpha=0.68,
            edgecolor="white",
            linewidth=0.25,
            zorder=2,
        )
        ax.hlines(d["fraction"].median(), xi - 0.24, xi + 0.24, color="#111111", lw=1.0, zorder=3)
    r = mainD.loc[gene]
    ax.set_title(
        f"{gene}: OR {r.OR:.2f} ({r.CI_low:.2f}-{r.CI_high:.2f}); BH q={r.q_BH:.3g}",
        fontsize=6.4,
    )
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["HC", "SSc"], fontsize=6.8)
    ax.set_xlim(-0.45, 1.45)
    ax.set_ylim(-0.03, 1.03)
    ax.grid(axis="y", color="#DDDDDD", linewidth=0.5, linestyle=":")
    fs.despine(ax)
    if i == 0:
        ax.set_ylabel("Positive-cell fraction", fontsize=7.4)
    else:
        ax.tick_params(axis="y", labelleft=False, left=False)
        ax.spines["left"].set_visible(False)
    if i < 2:
        ax.tick_params(axis="x", labelbottom=False)
fig.legend(
    handles=[
        Line2D(
            [0], [0], marker="o", color="w", markerfacecolor=color,
            markeredgecolor="white", ms=5.5, label=cohort,
        )
        for cohort, color in COHORT_COLORS.items()
    ],
    loc="lower left",
    bbox_to_anchor=(0.075, 0.012),
    ncol=5,
    fontsize=5.2,
    title="Panel d cohorts",
    title_fontsize=5.5,
)

# ===== E: Xenium boundary adjacency =====
axE = fig.add_subplot(gs[2, 1])
if E_PANEL.exists():
    axE.imshow(crop_white(mpimg.imread(E_PANEL), pad=25))
    axE.axis("off")
else:
    axE.text(0.5, 0.5, "Xenium panel missing", ha="center")
    axE.axis("off")
fig.suptitle(
    "Perivascular Notch-ligand candidates -> myofibroblast NOTCH2/3 -> HES1",
    fontsize=11,
    fontweight="bold",
    y=0.990,
)
fig.subplots_adjust(left=0.090, right=0.985, bottom=0.075, top=0.955)
panel_slots = {
    "A": gs[:2, 0],
    "B": gs[0, 1],
    "C": gs[1, 1],
    "D": gs[2, 0],
    "E": gs[2, 1],
}
for label, slot in panel_slots.items():
    bounds = slot.get_position(fig)
    fig.text(
        bounds.x0 - 0.032,
        bounds.y1 + 0.006,
        label,
        fontsize=13,
        fontweight="bold",
        ha="left",
        va="bottom",
    )
fs.save_fig(fig, str(OUT))
print(
    "DLL4 rank",
    dll4,
    "/",
    n_ligands,
    "| Figure 6d main OR:",
    {gene: round(float(mainD.loc[gene, "OR"]), 3) for gene in genes},
)
