#!/usr/bin/env python3
"""Build config/study_manifest.json and config/analysis_plan.json for the
trajectory-processing stage (make_analysis_trajectories.py).

The manifest is bound to the frozen release (RELEASE_MANIFEST.json) and the
analysis index generated by build_analysis_ndx.py. realizations[].run_directory
points at the release repNN directories so no 31 GB XTC is copied.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RELEASE = ROOT / "analysis_config_work" / "RELEASE_MANIFEST.json"
NDX = ROOT / "builds" / "analysis.ndx"
MANIFEST_TEMPLATE = ROOT / "config" / "study_manifest.template.json"
PLAN_TEMPLATE = ROOT / "config" / "analysis_plan.template.json"
PROTOCOL = ROOT / "config" / "production_protocol_hmr4fs_303K_v1.json"
OUT_MANIFEST = ROOT / "config" / "study_manifest.json"
OUT_PLAN = ROOT / "config" / "analysis_plan.json"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def contains_placeholder(value: object) -> bool:
    if isinstance(value, str):
        upper = value.upper()
        return any(token in upper for token in ("TODO", "TBD", "PENDING", "PLACEHOLDER"))
    if isinstance(value, dict):
        return any(contains_placeholder(item) for item in value.values())
    if isinstance(value, list):
        return any(contains_placeholder(item) for item in value)
    return False


def main() -> int:
    release = json.loads(RELEASE.read_text(encoding="utf-8"))
    protocol = json.loads(PROTOCOL.read_text(encoding="utf-8"))
    ndx_sha = sha256(NDX)
    print("release archive:", release["archive_sha256"][:16])
    print("analysis.ndx:", ndx_sha)

    manifest = json.loads(MANIFEST_TEMPLATE.read_text(encoding="utf-8"))
    model = manifest["global_model"]
    force_field = protocol["force_field"]
    ensemble = protocol["ensemble"]
    production = protocol["production"]
    model["temperature_k"] = ensemble["temperature_K"]
    model["force_field_protein"] = force_field["protein"]
    model["force_field_lipid"] = force_field["lipids"]
    model["force_field_ligand"] = force_field["ligand"]
    model["water_model"] = force_field["water"]
    construction = manifest["systems"][0]["construction"]
    construction["analysis_index"] = {
        "path": "builds/analysis.ndx", "sha256": ndx_sha}
    # bind construction archive and inputs from the release manifest
    by_path = {a["path"]: a for a in release["artifacts"]}
    construction["charmm_gui_archive"] = {
        "path": "o6u_md_release_3x500ns_v4.tgz", "sha256": release["archive_sha256"]}
    construction["starting_coordinates"] = {
        "path": "common/step5_input.gro",
        "sha256": by_path["common/step5_input.gro"]["sha256"]}
    construction["topology"] = {
        "path": "common/topol.top", "sha256": by_path["common/topol.top"]["sha256"]}
    construction["index"] = {
        "path": "common/index.ndx", "sha256": by_path["common/index.ndx"]["sha256"]}
    construction["production_mdp"] = {
        "path": "rep01/production_500ns.mdp",
        "sha256": by_path["rep01/production_500ns.mdp"]["sha256"]}
    # Realization seeds and thermodynamic controls come only from the protocol
    # frozen before production, never from the legacy template defaults.
    realization_contract = {item["id"]: item for item in protocol["realizations"]}
    for real in manifest["systems"][0]["realizations"]:
        frozen = realization_contract[real["id"]]
        real["velocity_seed"] = frozen["velocity_seed"]
        real["thermostat_seed"] = frozen["thermostat_seed"]
        real["run_directory"] = real["id"]  # release root holds repNN/ with work/
    simulation = manifest["simulation"]
    simulation["time_step_ps"] = ensemble["production_time_step_ps"]
    simulation["hydrogen_mass_repartitioning"] = force_field["hydrogen_mass_repartitioning"]
    simulation["constraints"] = ensemble["constraints"]
    simulation["electrostatics"] = ensemble["electrostatics"]
    simulation["pressure_coupling"] = ensemble["pressure_coupling"]
    simulation["production_ns"] = production["duration_ns_per_realization"]
    simulation["analysis_window_ns"] = [200.0, 500.0]
    mdp_contract = simulation["production_mdp_contract"]
    mdp_contract.update({
        "integrator": ensemble["integrator"],
        "thermostat": ensemble["thermostat"],
        "thermostat_groups": ensemble["temperature_groups"],
        "barostat": ensemble["barostat"],
        "constraint_algorithm": ensemble["constraint_algorithm"],
        "com_removal_groups": ["SOLU_MEMB", "SOLV"],
    })
    cadence = mdp_contract["output_cadence_steps"]
    cadence["nstxout_compressed"] = int(
        round(production["trajectory_interval_ps"] / simulation["time_step_ps"])
    )
    cadence["nstenergy"] = int(
        round(production["energy_interval_ps"] / simulation["time_step_ps"])
    )
    cadence["nstlog"] = int(
        round(production["log_interval_ps"] / simulation["time_step_ps"])
    )
    manifest["protocol_record"] = {
        "path": "config/production_protocol_hmr4fs_303K_v1.json",
        "sha256": sha256(PROTOCOL),
        "protocol_id": protocol["protocol_id"],
    }
    # Artifact/report placeholders are intentionally retained until the
    # post-production evidence binder resolves them. Never false-release a
    # manifest merely because the protocol fields have been refreshed.
    manifest["manifest_status"] = (
        "draft_pending_artifact_binding"
        if contains_placeholder(manifest)
        else "ready_for_trajectory_processing"
    )
    OUT_MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    OUT_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    m_sha = sha256(OUT_MANIFEST)

    plan = json.loads(PLAN_TEMPLATE.read_text(encoding="utf-8"))
    plan["analysis_status"] = "draft_pending_qc_and_trajectory_binding"
    plan["temperature_k"] = 303.15  # HMR amendment protocol
    plan["trajectory_processing"]["groups"] = {
        "system": "System",
        "complex": "Protein_O6U",
        "fit": "PSEN1_Core",
        "analysis_output": "Protein_O6U",
        "pbc_invariance_protein_heavy": "Protein_Heavy",
        "pbc_invariance_ligand_heavy": "O6U_Heavy",
    }
    plan["trajectory_processing"]["fixed_window_ns"] = [200.0, 500.0]
    plan["trajectory_processing"]["snapshot_times_ns"] = [200.0, 350.0, 500.0]
    plan["input_contract"]["fit_selection_id"] = "PSEN1_Core_13_contact_CA"
    plan["input_contract"]["atom_selection_id"] = "Protein_O6U_20867"
    plan["eligibility_gate"]["all_realizations_passed_qc_and_stationarity"] = False
    plan["eligibility_gate"]["qc_and_stationarity_report_sha256"] = "TODO_BIND_AFTER_SEALING"
    OUT_PLAN.parent.mkdir(parents=True, exist_ok=True)
    OUT_PLAN.write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
    p_sha = sha256(OUT_PLAN)
    print(f"WROTE {OUT_MANIFEST} sha256={m_sha}")
    print(f"WROTE {OUT_PLAN} sha256={p_sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
